services:  #key that define all contains req for app
  db:      
    image: postgres
    environment:                            #configration batata hai host se lekr container ko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"                   
    
  backend:
    build: . 
    image: sourabhj11/expense_repo:latest
    environment:                               
      DATABASE_URL: postgresql://postgres:1234@db:5432/postgres
    depends_on:
      - db
    
    ports:
      - "8000:8000"
